spider:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  a_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: a_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  b_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: b_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  c_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: c_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  FL_a_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: FL_a_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  FL_b_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: FL_b_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  FL_c_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: FL_c_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}