<?xml version="1.0"?>
<robot name="spider" xmlns:xacro="http://www.ros.org/wiki/xacro">
<xacro:include filename="$(find spider_description)/materials/materials.xacro" />
<xacro:include filename="$(find spider_description)/urdf/spider.gazebo" />
<xacro:include filename="$(find spider_description)/macros/inertia.xacro" />
<xacro:include filename="$(find spider_description)/macros/leg.xacro" />

<xacro:property name="leg_a_length" value="0.07"/>
<xacro:property name="leg_b_length" value="0.12"/>
<xacro:property name="leg_radius" value="0.005"/>
<xacro:property name="leg_mass" value="0.05"/>

<xacro:property name="servo_length" value="0.02"/>
<xacro:property name="servo_width" value="0.01"/>
<xacro:property name="servo_height" value="0.03"/>
<xacro:property name="servo_mass" value="0.1"/>

<xacro:property name="body_length" value="0.15"/>
<xacro:property name="body_width" value="0.10"/>
<xacro:property name="body_height" value="0.05"/>
<xacro:property name="body_mass" value="0.5"/>

<xacro:property name="servo_effort" value="1000"/>
<xacro:property name="servo_velocity" value="3"/>

<!-- Links -->

<link name="base_link"/>

<link name="body">
	<collision>
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<geometry>
			<box size="${body_length} ${body_width} ${body_height}"/>
		</geometry>
	</collision>

	<visual>
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<geometry>
			<box size="${body_length} ${body_width} ${body_height}"/>
		</geometry>
		<material name="white"/>
	</visual>

	<xacro:box_inertial m="${body_mass}" x="${body_length}" y="${body_width}" z="${body_height}"/>
</link>

<make_leg name="FL" reflect="0" parent="body" xpos="${body_length/2}"/>
<make_leg name="FR" reflect="1" parent="body" xpos="${body_length/2}"/>
<make_leg name="ML" reflect="0" parent="body" xpos="${0}"/>
<make_leg name="MR" reflect="1" parent="body" xpos="${0}"/>
<make_leg name="BL" reflect="0" parent="body" xpos="${-body_length/2}"/>
<make_leg name="BR" reflect="1" parent="body" xpos="${-body_length/2}"/>

<joint name="base_joint" type="fixed">
	<parent link="base_link"/>
	<child link="body"/>
</joint>

</robot>