<?xml version="1.0"?>
<robot name="spider" xmlns:xacro="http://www.ros.org/wiki/xacro">
<macro name="make_leg" params="name reflect parent xpos">
  <link name="${name}_a_servo">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${servo_length} ${servo_width} ${servo_height}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${servo_length} ${servo_width} ${servo_height}"/>
      </geometry>
      <material name="blue"/>
    </visual>

    <xacro:default_inertial m="${servo_mass}"/>
  </link>

  <link name="${name}_b_servo">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${servo_length} ${servo_width} ${servo_height}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${servo_length} ${servo_width} ${servo_height}"/>
      </geometry>
      <material name="blue"/>
    </visual>

    <xacro:default_inertial m="${servo_mass}"/>
  </link>

  <link name="${name}_proximal_leg">
    <collision>
      <origin xyz="0 0 ${leg_a_length/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${leg_a_length}" radius="${leg_radius}"/>
      </geometry>
    </collision>
    
    <visual>
      <origin xyz="0 0 ${leg_a_length/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${leg_a_length}" radius="${leg_radius}"/>
      </geometry>
      <material name="white"/>
    </visual>
    
    <xacro:default_inertial m="${leg_mass}"/>
  </link>

  <link name="${name}_distal_leg">
    <collision>
      <origin xyz="0 0 ${leg_b_length/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${leg_b_length}" radius="${leg_radius}"/>
      </geometry>
    </collision>
    
    <visual>
      <origin xyz="0 0 ${leg_b_length/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${leg_b_length}" radius="${leg_radius}"/>
      </geometry>
      <material name="white"/>
    </visual>
    
    <xacro:default_inertial m="${leg_mass}"/>
  </link>

  <joint name="${name}_leg_fix" type="fixed">
    <parent link="body"/>
    <child link="${name}_a_servo"/>
    <origin xyz="${xpos} ${(-1)*((body_width+servo_length)/2)*(2*reflect-1)} 0" rpy="0 -1.57 ${(-1)*(1.57)*(2*reflect-1)}"/>
  </joint>

  <joint name="${name}_a_joint" type="revolute">
    <parent link="${name}_a_servo"/>
    <child link="${name}_b_servo"/>
    <origin xyz="${(servo_length+servo_width)/2} 0 ${-servo_height/4}" rpy="0 0 ${(1.57)*(2*reflect-1)}"/>
    <axis xyz="0 1 0"/>
    <limit lower="-1.57" upper="1.57" effort="${servo_effort}" velocity="${servo_velocity}"/>
  </joint>

  <joint name="${name}_b_joint" type="revolute">
    <parent link="${name}_b_servo"/>
    <child link="${name}_proximal_leg"/>
    <origin xyz="${(servo_length+leg_radius)/2} 0 ${-servo_height/4}" rpy="${(1.57)*(2*reflect-1)} 0 0"/>
    <axis xyz="1 0 0"/>
    <limit lower="${(1-reflect)*(-3.14)+(reflect)*(0)}" upper="${(1-reflect)*(0)+(reflect)*(3.14)}" effort="${servo_effort}" velocity="${servo_velocity}"/>
  </joint>

  <joint name="${name}_c_joint" type="revolute">
    <parent link="${name}_proximal_leg"/>
    <child link="${name}_distal_leg"/>
    <origin xyz="0 ${(-1)*(2*reflect-1)*(leg_radius*2)} ${leg_a_length}" rpy="0 3.14 0"/>
    <axis xyz="1 0 0"/>
    <limit lower="${(1-reflect)*(-3.14)+(reflect)*(0)}" upper="${(1-reflect)*(0)+(reflect)*(3.14)}" effort="${servo_effort}" velocity="${servo_velocity}"/>
  </joint>

  <transmission name="${name}_a_transmission">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="${name}_a_joint">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="${name}_a_joint_leg_actuator">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
      <mechanicalReduction>10</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="${name}_b_transmission">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="${name}_b_joint">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="${name}_b_joint_leg_actuator">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
      <mechanicalReduction>10</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="${name}_c_transmission">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="${name}_c_joint">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="${name}_c_joint_leg_actuator">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
      <mechanicalReduction>10</mechanicalReduction>
    </actuator>
  </transmission>

  <gazebo reference="${name}_distal_leg">
    <mu1 value="10.0" />
    <mu2 value="1.0" />
    <fdir1 value="1 0 0"/>
    <kp value="1000000.0"/>
    <kd value="100.0"/>
    <material>Gazebo/Black</material>
    <turnGravityOff>false</turnGravityOff>
  </gazebo>
</macro>
</robot>